
<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <title>Citát dne</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="/css/style.css">
    <link rel="icon" type="image/png" href="/images/favicon.png">
</head>

<body>
<div>
<h1>${citat}</h1>
<div>

<img class="fotka" src="/images/Obrazek-${obrazek}.jpg" />
</div>

<div>Ukaz fotku: <span>${obrazek}</span></div>
</div>

<blockquote><h1>${citat}</h1></blockquote>


</body>
</html>
